CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS banned_names (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    UNIQUE (name, category_id)
);

INSERT INTO categories (name)
VALUES
    ('Elektronika'),
    ('Spożywcze'),
    ('Meble')
ON CONFLICT (name) DO NOTHING;

INSERT INTO banned_names (name)
VALUES
    ('Zakazany produkt'),
    ('Nielegalne'),
    ('Fake')
ON CONFLICT (name) DO NOTHING;

INSERT INTO products (name, category_id, price)
VALUES
    ('Laptop', (SELECT id FROM categories WHERE name = 'Elektronika'), 3499.99),
    ('Smartfon', (SELECT id FROM categories WHERE name = 'Elektronika'), 1999.00),
    ('Kawa ziarnista', (SELECT id FROM categories WHERE name = 'Spożywcze'), 49.90),
    ('Herbata zielona', (SELECT id FROM categories WHERE name = 'Spożywcze'), 12.50),
    ('Biurko', (SELECT id FROM categories WHERE name = 'Meble'), 599.00),
    ('Krzesło obrotowe', (SELECT id FROM categories WHERE name = 'Meble'), 399.99)
ON CONFLICT (name, category_id) DO NOTHING;
