import os
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "appdb")
DB_USER = os.getenv("DB_USER", "appuser")
DB_PASSWORD = os.getenv("DB_PASSWORD", "apppassword")

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = (
        f"postgresql+psycopg://{DB_USER}:{DB_PASSWORD}"
        f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    )

engine_kwargs = {"echo": True}
if DATABASE_URL.startswith("sqlite"):
    engine_kwargs["connect_args"] = {"check_same_thread": False}

engine = create_engine(
    DATABASE_URL,
    **engine_kwargs
)


# ORM BASE
class Base(DeclarativeBase):
    pass


# SESSION FACTORY
SessionLocal = sessionmaker(
    bind=engine,
    autoflush=False,
    autocommit=False
)

# FASTAPI DEPENDENCY
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def ensure_notifications_schema_compatibility() -> None:
    """
    Keeps existing Postgres databases compatible with current notifications ORM.
    This is a lightweight migration for class project purposes.
    """
    if not DATABASE_URL.startswith("postgresql"):
        return

    with engine.begin() as connection:
        connection.exec_driver_sql(
            """
            ALTER TABLE IF EXISTS notifications
            ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR
            """
        )
        connection.exec_driver_sql(
            """
            UPDATE notifications
            SET idempotency_key = 'notif_legacy_' || id::text
            WHERE idempotency_key IS NULL
            """
        )
        connection.exec_driver_sql(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_idempotency_key
            ON notifications (idempotency_key)
            """
        )


def ensure_cart_schema_compatibility() -> None:
    """
    Keeps existing Postgres databases compatible with the cart/order feature set.
    This creates new tables if they are missing and backfills stock for seeded products.
    """
    if not DATABASE_URL.startswith("postgresql"):
        return

    with engine.begin() as connection:
        connection.exec_driver_sql(
            """
            ALTER TABLE IF EXISTS products
            ADD COLUMN IF NOT EXISTS stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0)
            """
        )
        connection.exec_driver_sql(
            """
            CREATE TABLE IF NOT EXISTS carts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_carts_operator UNIQUE (operator_id)
            )
            """
        )
        connection.exec_driver_sql(
            """
            CREATE TABLE IF NOT EXISTS cart_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cart_id INTEGER NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
                product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                quantity INTEGER NOT NULL CHECK (quantity > 0),
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
            )
            """
        )
        connection.exec_driver_sql(
            """
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
                order_number VARCHAR NOT NULL UNIQUE,
                status VARCHAR NOT NULL DEFAULT 'PENDING',
                total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        connection.exec_driver_sql(
            """
            CREATE TABLE IF NOT EXISTS order_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
                product_name VARCHAR NOT NULL,
                unit_price NUMERIC(10, 2) NOT NULL,
                quantity INTEGER NOT NULL CHECK (quantity > 0),
                line_total NUMERIC(10, 2) NOT NULL
            )
            """
        )
        connection.exec_driver_sql(
            """
            CREATE INDEX IF NOT EXISTS idx_carts_operator_id
            ON carts(operator_id)
            """
        )
        connection.exec_driver_sql(
            """
            CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id
            ON cart_items(cart_id)
            """
        )
        connection.exec_driver_sql(
            """
            CREATE INDEX IF NOT EXISTS idx_orders_operator_id
            ON orders(operator_id)
            """
        )
        connection.exec_driver_sql(
            """
            CREATE INDEX IF NOT EXISTS idx_order_items_order_id
            ON order_items(order_id)
            """
        )
        connection.exec_driver_sql(
            """
            CREATE TABLE IF NOT EXISTS processed_commands (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                command_name VARCHAR NOT NULL,
                idempotency_key VARCHAR NOT NULL,
                operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_processed_command_key
                    UNIQUE (command_name, idempotency_key)
            )
            """
        )
        connection.exec_driver_sql(
            """
            CREATE INDEX IF NOT EXISTS idx_processed_commands_key
            ON processed_commands(command_name, idempotency_key)
            """
        )
        connection.exec_driver_sql(
            """
            UPDATE products
            SET stock_quantity = CASE name
                WHEN 'Laptop' THEN 25
                WHEN 'Smartfon' THEN 40
                WHEN 'Kawa ziarnista' THEN 120
                WHEN 'Herbata zielona' THEN 200
                WHEN 'Biurko' THEN 15
                WHEN 'Krzesło obrotowe' THEN 30
                ELSE stock_quantity
            END
            WHERE stock_quantity = 0
            """
        )
